import React from "react";
import { useParams } from "react-router-dom";
import Thanjavur from '../img/thanvajur.jpeg';
import Madurai from '../img/meenasi_temple.jpg'
import Adikumbeswarar from '../img/Adi_Kumbeswarar_Temple.jpg'
import SriRanganathaswamy from '../img/Sri_Ranganathaswamy.jpg'
import SriRajagopala from '../img/Sri_Rajagopala.jpg';
import Kanchi_Kailasanathar from '../img/Kanchi_Kailasanathar.jpg';
import Srivilliputhur_Andal from '../img/Srivilliputhur_Andal.jpg';
import Kumari_Amman from '../img/Kumari_Amman.jpg';
import back_temple from '../img/back_temple.avif';

function ExplorePage({ ima }) {
  const { index } = useParams(); 

  // Ensure that index is a valid number
  const imageIndex = parseInt(index);

  const images = [
    {image : Madurai,place:"Meenashi Amman Temple",note:'Meenakshi Amman Temple, also called Meenakshi Temple or Meenakshi Sundareswarar Temple, temple complex in Madurai, Tamil Nadu state, India, said to originally date as far back as the 4th century CE but in its present form built in the 16th–17th centuries. According to Hindu legend, the god Shiva came to Madurai in the form of Sundareswarar to marry Meenakshi, the daughter of the Pandya ruler; Meenakshi was a manifestation of the goddess Parvati. The Meenakshi Amman Temple is dedicated to their union. The massive temple is enclosed by high walls entered through soaring gopuras, or gateway towers. Inside are colonnades, columned mandapas (halls, some of which were used for shops, storerooms, and stables), a sacred tank, lesser shrines, and, at the centre, the two main shrines to Sundareswarar and Meenakshi. The gopuras are some of the most elaborately decorated in India. Brightly painted, they are completely covered with figures of divinities, celestial beings, monster masks, guardians, and animal mounts. The tallest of the 14, the southern gopura, rises to more than 170 feet (52 m).Within the temple complex is the magnificent Aiyaram Kal Mandapa (Thousand-Pillar Hall), which in fact contains 985 columns carved with divinities, female musicians, and attendant figures. The Pottamarai Kulam (Golden Lotus Pond), a large pool where devotees can bathe in holy water, is surrounded by a colonnade whose walls are decorated with murals depicting the miracles Shiva performed in Madurai. A doorway in the west wall leads to the Meenakshi shrine. This stands in its own enclosure, within which are several subsidiary shrines, together with the bedchamber, where the image of Sundareswarar is brought every night from its own shrine.This is a living temple. Every week golden figures of Meenakshi and Sundareswarar are seated on a swing and hymns are sung; at the annual Teppa festival their images are mounted on floats and pulled back and forth over the Pottamarai Kulam; and the goddess’s wedding festival is celebrated each year for twelve days in the month of Chaitra (April/May).'},
    {image : Thanjavur,place:"Thanjavur Periya Kovil",note:'Built by Raja Raja Chola I in 1010 AD, Brihadeshwara Temple is an ancient temple at Thanjavur in Tamil Nadu. The deity of the temple is Lord Shiva—in his dancing pose—who is called the Nataraj. The temple is also known as Rajeswara Temple, Rajarajeswaram and Periya Kovil. The temple was built, like a fortress on the shores of a river, by the king to grace the Chola Empire. This thousand-year-old temple is now part of the UNESCO World Heritage Site adding to its exceptional historical and cultural value. The temple is a magnificent architectural construct that will never stop surprising anyone visiting the temple. Built using over 130,000 tons of granite, this fabulous structure shows the architectural prowess and affinity of the South Indian kings.The major attraction of the temple is the 216-feet-tall tower that is built above the Sanctum of the temple. This flamboyant tower can be seen by anyone entering the city from afar. Another breathtaking thing that will sure stupefy the visitor is the magnificent Nandi statue built at the temple; it is about two meters in height, six meters in length and two-and-half meters in width, and weighs around a whopping 20 tons for a statue built from a single stone. Various postures of the famous classical dance, Barathanatyam, are carved carefully on the exterior walls of the upper storey of the temple.There are several shrines added to the temple by most of the following rulers such as the Pandyas, the Vijayanagara rulers and the Marathas, too. The temple architecture marvels at housing a myriad of surprises for everyone taking a look at this great temple. Another important architectural feature of the temple is that the shadow of the temple never falls on the ground at noon. The architecture of the temple is done so cleverly that the temple casts no shadow on the ground when the sun is at its peak. This is a phenomenon that attracts thousands of tourists and architectural enthusiasts from across the world to unravel the architectural mystery of the temple'},
    {image : Adikumbeswarar,place:" Adikumbeswarar Temple",note:'The historical background of Kumbeswarar temple in Kumbakonam is a profound and intricate one. It is widely believed that the Cholas constructed this temple in the 9th century CE, and subsequently, the Nayaks refurbished it in the 16th century. However, there exists evidence suggesting that the temple might have been erected even earlier, possibly as far back as the 6th century CE. The temple, an eminent shrine dedicated to Shiva, holds great significance as one of the foremost Shiva temples in Tamil Nadu.It is recognized as one of the 108 Paadal Petra Sthalams, the sacred locations mentioned in the 7th century Tamil Saiva canonical work, the Tevaram, authored by revered Tamil saint poets known as the Nayanmars. The temple derives its name from the principal deity, Kumbeswarar, which signifies “Lord of the vessel”. As per legend, Shiva created the vessel to contain the elixir of immortality. During a tremendous flood, the vessel was set afloat on the ocean and eventually came to rest in Kumbakonam. The nectar spilled from the vessel and formed the Mahamaham tank, situated close to the temple. Throughout the ages, the temple has undergone numerous transformations. Initially constructed in the Dravidian architectural style, it was later revamped in the Vijayanagara style. The temple complex now encompasses a sprawling area measuring 30,181 square feet (2,803.9 square meters) and comprises four entrance towers, renowned as gopurams. The tallest among these gopurams is the eastern tower, towering at a height of 125 feet. The temple garners immense popularity as a pilgrimage site, particularly during the grand Mahamaham festival, which occurs every 12 years. This festival is believed to absolve all sins and attracts millions of devotees from across India. The Adi Kumbeswarar Temple boasts exquisite beauty and historic significance, cementing its status as one of the foremost religious destinations in Tamil Nadu. It is an essential visit for individuals intrigued by Hindu architecture or the cultural heritage of South India.'},
    {image : SriRanganathaswamy,place:"Sri Ranganathaswamy Temple",note:' Sri Ranganathaswamy Temple, also known as Thiruvaranga Tirupati, is one of the most illustrious Vaishnav[1] temples in the country, dedicated to Ranganatha, a reclining form of Hindu deity, Bhagwan (God or Lord) Vishnu. Situated in an ethereal setting on the island of Srirangam that is bounded by the two rivers of Cauvery and Kollidam (a tributary of Cauvery), this living temple and sacred centre of pilgrimage is counted as the first and foremost among the 108 Divya Desams dedicated to Bhagwan Vishnu.More importantly, it is not just a temple but a temple-town, unique in its Sapta-Prakaram[2] formation, a temple centred settlement pattern that comprises of Sapta (seven)[3] concentric rectangular enclosures or prakarams[4] formed by thick and huge rampart walls that run round the sanctum sanctorum in which the deity presides. While the inner five enclosures of the complex constitute the temple, the outer two enclosures function as the settlement. Thus, the distinction between the temple and the settlement gets blurred and the temple is also referred to as Srirangam many a times. This Temple-Town typology is unique to this part of the world and Sri Ranganathaswamy Temple is an exceptional example of the same.Constructed in the Dravidian style of architecture, the Temple Complex is massive in scale and spread over 156 acres (63.131 hectares). According to some scholars, this makes Sri Ranganathaswamy Temple the largest Functioning Temple in the World[5] and is often found ranked amongst the largest religious complexes of the world, including the Potala Palace in Lhasa, Tibet, Angkor Wat in Cambodia, Borobodur in Indonesia, Machu Picchu in Peru and the Vatican City.Apart from the 7 prakarams with massive walls, the Temple Complex has 21 very colourful sculpted gopurams (consecrated gateways with towers), 50 sub shrines, 9 sacred pools, gilded Vimana (dome) over the sanctum sanctorum of the presiding deity, and other interesting features such as fresco paintings. Active interchange of human values was happening between the public and rulers in planning, designing, executing and using the Temple complex.'},

    {image : SriRajagopala,place:"Sri RajagopalaTemple",note:'Sri Rajagopalaswamy Temple, also referred to as Santhana Rajagopalaswamy Temple, is a Hindu temple in Rajamadam Village in the Indian state of Tamil Nadu.'},
    {image : Kanchi_Kailasanathar,place:"Kanchi Kailasanathar Temple",note:'Kanchi Kailasanathar Temple is an important religious site is located on the banks of the Vedavathi River, at the western limits, facing the east side in the Kanchipuram city of Tamil Nadu.'},
    {image : Srivilliputhur_Andal,place:"Srivilliputhur Andal Temple",note:'The Srivilliputhur Andal Temple in Srivilliputhur, a town in Virudhunagar district in the South Indian state of Tamil Nadu, is dedicated to the Hindu god Vishnu.'},
    {image : Kumari_Amman,place:"Kumari Amman Temple, Kanyakumari",note:'Kumari Amman temple is 3000 years old and is for Devi Kanyakumari. She is the virgin goddess who stands strong protecting her devotees'},
  
  ];
  const image = images[imageIndex];

  return (
    <div>
        <div className="w-100 text-center " >
        <h2 className="py-3 text-info" >{image.place}</h2>
        </div>
    <div className="row overflow-hidden" >
        <div className="col-4 p-5">
      
      <img src={image.image} alt={image.place} style={{width:'710px'}} />
      </div>
    <div className="col-8 p-5">
      <p style={{textIndent:40,backgroundColor:'transparent',fontSize:17}}>{image.note}</p>
      </div>
    </div>
    </div>
  );
}

export default ExplorePage;


